/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cadillac_2077.gltf
Author: salvatore.butera1998 (https://sketchfab.com/salvatore.butera1998)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cadillac-2077-f1b7fc785f8d4e49810b27e0eb50740f
Title: Cadillac 2077
*/

import React, { useRef } from 'react'
import { Circle, MeshReflectorMaterial, useGLTF } from '@react-three/drei'

export function Cadillac(props) {
  const { nodes, materials } = useGLTF('/cadillac_2077.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.45} position={[0.3,-0.3,0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_14.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.MEtallic} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_37.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_38.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_39.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_40.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_41.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_42.geometry} material={materials.MEtallic} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_86.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_87.geometry} material={materials.GlassBReaksLight} />
            <mesh geometry={nodes.Object_88.geometry} material={materials.TurnSignal} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_102.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_103.geometry} material={materials.BrakeLights} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_125.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_126.geometry} material={materials.FOgLight} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_132.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_133.geometry} material={materials.Contachilometri} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_155.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_156.geometry} material={materials.MEtallic} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_160.geometry} material={materials.MEtallic} />
            <mesh geometry={nodes.Object_161.geometry} material={materials.Cruscotto} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_163.geometry} material={materials.sedili} />
            <mesh geometry={nodes.Object_164.geometry} material={materials.Sedili2} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_166.geometry} material={materials.sedili} />
            <mesh geometry={nodes.Object_167.geometry} material={materials.Sedili2} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_169.geometry} material={materials.sedili} />
            <mesh geometry={nodes.Object_170.geometry} material={materials.Sedili2} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_178.geometry} material={materials.sedili} />
            <mesh geometry={nodes.Object_179.geometry} material={materials.Sedili2} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_183.geometry} material={materials.sedili} />
            <mesh geometry={nodes.Object_184.geometry} material={materials.Sedili2} />
          </group>
          <group position={[0.08, -0.33, 5.23]}>
            <mesh geometry={nodes.Object_186.geometry} material={materials.sedili} />
            <mesh geometry={nodes.Object_187.geometry} material={materials.Sedili2} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.GlassLights} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.GlassLights} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.GlassWindSHield} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.DarkBlackengine} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_76.geometry} material={materials.GlassWindSHield} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_84.geometry} material={materials.GlassBReaksLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_90.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.FOgLight} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.Carrozzeria} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_111.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_113.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_117.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_119.geometry} material={materials.moquet} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_121.geometry} material={materials.Cruscotto} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_123.geometry} material={materials.sedili} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_128.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_130.geometry} material={materials.Cruscotto} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_135.geometry} material={materials.Contachilometri} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_137.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_139.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_141.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_143.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_145.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_147.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_149.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_151.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_153.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_158.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_176.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
          <mesh geometry={nodes.Object_181.geometry} material={materials.MEtallic} position={[0.08, -0.33, 5.23]} />
        </group>
      </group>
      <Circle args={[12.75, 36, 36]} rotation-x={-Math.PI / 2} position={[1, -1.39, 0]}>
        <MeshReflectorMaterial
          resolution={1024}
          blur={[400, 50]}
          mirror={0}
          mixBlur={0.75}
          mixStrength={10}
          transparent
          opacity={0.5}
          color="#555"
          metalness={0.95}
          roughness={1}
        />
      </Circle>
    </group>
  )
}

useGLTF.preload('/cadillac_2077.gltf')
